import Head from "next/head";
import { createClient } from "contentful";
import Link from "next/link";
import herobox from "../img/herobox.jpg";
import Image from "next/image";

export async function getStaticProps() {
  const client = createClient({
    space: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID,
    accessToken: process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN,
  });

  const res = await client.getEntries({
    content_type: "blogPost",
  });
  return {
    props: {
      blogs: res.items,
    },
  };
}

export default function Home({ blogs }) {
  console.log(blogs);

  return (
    <section id="homepage">
      <Head>
        <title>Memento Code | Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="homepage">
        {/* <div className="herobox">
          <Image src={herobox} layout="responsive" height="300px"></Image>
        </div> */}
        <div className="blogs-container">
          {blogs.map((blog) => (
            <div className="blog" key={blog.sys.id}>
              <Link href={"/blogs/" + blog.fields.slug}>
                <div className="blog">
                  <Image
                    src={"http:" + blog.fields.heroImage.fields.file.url}
                    width="300px"
                    height="200px"
                  ></Image>
                  <h1>{blog.fields.title}</h1>
                  <small className="small author">
                    {blog.fields.author.fields.name}
                  </small>
                  <p className="description">{blog.fields.description}</p>
                </div>
              </Link>
            </div>
          ))}
        </div>
      </main>
    </section>
  );
}
